[program:examguard]
environment=PROC_NAME="%(program_name)s",EXAMGUARD_HOST="__BACKEND_HOST__",EXAMGUARD_PORT="__BACKEND_PORT__"
command=__EXAMGUARD_ROOT__/scripts/vast/supervisor_examguard.sh
autostart=true
autorestart=unexpected
startsecs=5
stopsignal=TERM
stopwaitsecs=20
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
